version: '3.7'

services:
  program:
    image: program
    volumes: 
      - ./program/data:/usr/src/app/data
    build: ./program/
  
  pytorch:
    image: pytorch
    deploy:
      replicas: 3
    volumes: 
      - ./pytorch/data:/usr/src/app/data
    build: ./pytorch/